version: "3.0"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../:/workspaces:cached
    command: sleep infinity
